### PR TITLE
fix relay proxy config - support parquet for data collection

### LINKED ISSUE #157: (feature) support parquet for data collection
# Requirements
Today the module can collect the data in 2 formats _(`csv` and `json`)_, it would be great to be able to export the data in  [parquet format](https://parquet.apache.org/) to help for future analyses.

The library [`xitongsys/parquet-go`](https://github.com/xitongsys/parquet-go) seems to be a good candidate to handle the format.

### PR DESCRIPTION
**Pull request by dhanusaputra**
# Description

fix not able to customize `parquetCompressionCodec` in relay-proxy

# Changes include
- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking changes (change that is not backward-compatible and/or changes current functionality)

# Closes issue(s)

Resolve #157 

# Checklist
- [x] I have tested this code
- [x] I have added unit test to cover this code
- [ ] I have updated the documentation (`README.md` and `/website/docs`)
- [x] I have followed the [contributing guide](CONTRIBUTING.md)

### CODE REVIEW

File: cmd/relayproxy/main.go [hunk 1]
```diff
@@ -2,9 +2,9 @@ package main
 
 import (
 	"fmt"
-	"github.com/spf13/pflag"
 	"os"
 
+	"github.com/spf13/pflag"
```
Comment (thomaspoignant) [inline cmd/relayproxy/main.go:7]: it will be great to avoid this kind of change in the PR.

**Review by thomaspoignant — APPROVED** [review]

File: cmd/relayproxy/config/exporter.go [hunk 2]
```diff
@@ -1,22 +1,27 @@
...
+	CsvTemplate             string            `mapstructure:"csvTemplate" koanf:"csvtemplate"`
+	Bucket                  string            `mapstructure:"bucket" koanf:"bucket"`
+	Path                    string            `mapstructure:"path" koanf:"path"`
+	EndpointURL             string            `mapstructure:"endpointUrl" koanf:"endpointurl"`
+	Secret                  string            `mapstructure:"secret" koanf:"secret"`
+	Meta                    map[string]string `mapstructure:"meta" koanf:"meta"`
+	LogFormat               string            `mapstructure:"logFormat" koanf:"logformat"`
+	FlushInterval           int64             `mapstructure:"flushInterval" koanf:"flushinterval"`
+	MaxEventInMemory        int64             `mapstructure:"maxEventInMemory" koanf:"maxeventinmemory"`
+	ParquetCompressionCodec string            `mapstructure:"parquetcompressioncodec" koanf:"parquetCompressionCodec"`
```
Comment (thomaspoignant) [inline cmd/relayproxy/config/exporter.go:24]:
```suggestion
	ParquetCompressionCodec string            `mapstructure:"parquetCompressionCodec" koanf:"parquetcompressioncodec"`
```

**Review by thomaspoignant — APPROVED** [review]

File: cmd/relayproxy/config/exporter.go (hunk 2 above)
Comment (thomaspoignant) [reply cmd/relayproxy/config/exporter.go]: Everything should be lowercase in the koanf config to be able to be overridden in env variable.
