### PR TITLE
fix: error when JsonLogic panics

### LINKED ISSUE #4711: (bug) Internal server error when JsonLogic package pancis
### Observed behaviour

When using JsonLogic based targeting rules an internal server error is occurs if the underlying package returns an error. For example take flag with the following JsonLogic as targeting rule query:
```json
{
          "==": [
            "end",
            {
              "substr": [
                {
                  "var": "my_short_var"
                },
                -3
              ]
            }
          ]
        }
```
When evaluating the flag and not providing the variable `my_short_var` at all in the context or providing a variable that is only `2` characters (shorter than the -3 substring), the JsonLogic package panics because the array index is out of bounds. This line specifically in the underlying package panics: https://github.com/GeorgeD19/json-logic-go/blob/master/jsonlogic.go#L310
This results in an internal server error returned:
```
$ curl -X POST localhost:1031/ofrep/v1/evaluate/flags/my_flag --data '{"context": {"my_short_var": "ab"}}' --header 'Content-Type: application/json' 
{"message":"Internal Server Error"}
```

### Expected Behavior

As far as I know generally JsonLogic shouldn't return an any errors, but will just consider the expression falsey. This is for example how the javascript implementation handles it. So either the underlying package is patched to make sure it does not panic (I'm not sure if there are any other cases in which the package panics) or the panic is caught within go feature flag and when evaluating the flag the targeting rule is simply considered `false`.

### Steps to reproduce

See above

### PR DESCRIPTION
**Pull request by doriandekoning**
## Description
JsonLogic panics, panic not caught resulting in an internalservererror returned. Made the fix a bit more general, it will also catch any panics from `nikunjy` if it should ever throw some. 

## Closes issue(s)

Resolve #4711 

## Checklist
- [ ] I have tested this code
- [ ] I have added unit test to cover this code
- [ ] I have updated the documentation (`README.md` and `/website/docs`)
- [ ] I have followed the [contributing guide](CONTRIBUTING.md)
](https://github.com/thomaspoignant/go-feature-flag/issues/4711)

### CODE REVIEW

File: modules/core/flag/rule.go [hunk 1]
```diff
@@ -102,11 +102,23 @@ func (r *Rule) Evaluate(key string, ctx ffcontext.Context, flagName string, isDe
...
 	mapCtx := utils.ContextToMap(ctx)
+
+	// Catch any panics that may occur during evaluation
+	defer func() {
+		if r := recover(); r != nil {
+			slog.ErrorContext(context.Background(), "panic recovered while evaluating query",
+				slog.Any("panic", r),
+				slog.String("query", query),
+			)
+			success = false
```
Comment (thomaspoignant) [inline modules/core/flag/rule.go:118]: do we have to rename the result?
Can't we just return false here?

Comment (doriandekoning) [reply modules/core/flag/rule.go:118]: Yep, because it is a deferred function we cannot simply return the value because it will get discarded as far as I know.

Comment (thomaspoignant) [reply modules/core/flag/rule.go:118]: Ok no worries, I was just checking.
I will merge this PR.
